### ISSUE TITLE
Error Running GSM8K Script

### ISSUE THREAD

**Issue by jiadingfang** [Ber666/RAP#4]
I tried to run the gsm8k script on my one a4000 machine with a llama-7b checkpoint. I followed the instructions to install llama environment. My running command is
> CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node 4 --master-port 1054 run_gsm8k.py --llama-ckpt $LLAMA_CKPTS/7B --speedup-confidence-batch-size 2

The error message is:
> Traceback (most recent call last):
  File "run_gsm8k.py", line 5, in <module>
Traceback (most recent call last):
  File "run_gsm8k.py", line 5, in <module>
    from rap.models import QueryLlama
  File "/share/data/ripl/fjd/RAP/rap/models.py", line 8, in <module>
    from rap.models import QueryLlama
  File "/share/data/ripl/fjd/RAP/rap/models.py", line 8, in <module>
    class QueryLM(ABC):
  File "/share/data/ripl/fjd/RAP/rap/models.py", line 14, in QueryLM
    class QueryLM(ABC):
  File "/share/data/ripl/fjd/RAP/rap/models.py", line 14, in QueryLM
    def query_next_token(self, prompt: list[str]):
TypeError: 'type' object is not subscriptable
    def query_next_token(self, prompt: list[str]):
TypeError: 'type' object is not subscriptable

Any idea how to fix it? Thanks!

**Comment by wu-qing-157** [comment]
Please try any of the following:

1. Use python>=3.9, since list[...] is supported since then
2. Just delete the type hint `: list[str]`, including other appearances in the code

**Comment by wu-qing-157** [comment]
Feel free to reopen if still not resolved.
